### PR TITLE
Socialize rework

### PR DESCRIPTION
**Pull request by Sylensky**
A lot of things need do be done here:

- [ ] theming with new settings for ribbons, labels and modals
- [ ] darkmode implementation

Currently it applies mainly the defaultrevamp design..
for reference:
image

@PadowYT2 maybe you can help me with the settings? Iam not so familiar with how to get & use them.

### CODE REVIEW

**Comment by PadowYT2** [comment]
So confused, about what settings?

**Comment by Sylensky** [comment]
I mean template variables and the settings from the nexus module

**Comment by PadowYT2** [comment]
So confused, you mean to make dark mode enable and disable?

**Comment by Sylensky** [comment]
Yes but also using the settings below:
Screenshot_20211230_112631_com android chrome

**Pull request closed without merging**
